
admin_portada:
    pattern:  /
    defaults: { _controller: UsuariBundle:Default:admin }


admin_login:
    pattern:   /login
    defaults:  { _controller: UsuariBundle:Default:login }


admin_login_check:
    pattern:   /login_check


admin_logout:
    pattern:   /logout