usuari_login:
    path:     /login
    defaults: { _controller: UsuariBundle:Default:login }

usuari_login_check:
    path:     /login_check

usuari_registre:
   path:     /registre
   defaults: { _controller: UsuariBundle:Default:registre }

usuari_logout:
   path:     /logout

usuari_torneig:
   path:     /torneig
   defaults: { _controller: UsuariBundle:Default:torneig }

usuari_torneig_exacte:
    path:    /torneig-{slug}
    defaults: { _controller: UsuariBundle:Default:torneig_exacte }

usuari_torneig_final:
    path:    /torneig-{slug}
    defaults: { _controller: UsuariBundle:Default:torneig_final }

torneig_registre:
    path:    /torneig-{slug}
    defaults:  { _controller: UsuariBundle:Default:insertartorneig }

UsuariBundle_torneig:
        resource: "@UsuariBundle/Resources/config/routing/torneig.yml"
        prefix:   /torneig
#usuari_tornejos:
#    path:     /login
#    defaults: { _controller: UsuariBundle:Default:login }

